# Weave
- name: Get Kubernetes version for Weave installation.
  shell: kubectl version | base64 | tr -d '\n'
  changed_when: false
  register: kubectl_version
  when: kubernetes_pod_network.cni == 'weave'

- name: Configure Weave networking.
  command: '{{ item }}'
  with_items:
    - 'kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{ kubectl_version.stdout_lines[0] }}'
  register: weave_result
  changed_when: "'created' in weave_result.stdout"
  when:
    - not kubernetes_init_stat.stat.exists
  environment:
    https_proxy: '{{ kubernetes_https_proxy }}'