---
# handlers file for cri-o
- name: cri_o | systemctl restart systemd-modules-load.service
  service:
    name: "systemd-modules-load.service"
    state: "restarted"
  changed_when: false
  ignore_errors: true

- name: cri_o | sysctl --system
  command: sysctl --system
  changed_when: false
  ignore_errors: true